export type { CryptoData } from './CryptoData.ts';
export type { DollarQuoteData } from './DollarQuoteData.ts';
export type { NavLink } from './NavLink.ts';
export type { NewsItem } from './NewsItem.ts';
export type { RepositoryData } from './RepositoryData.ts';
export type { SkillsData } from './SkillsData.ts';
export type { Testimonial } from './Testimonial.ts';
export type { TimelineItem } from './TimelineItem.ts';
export type { WeatherData } from './WeatherData.ts';